const SERVER_NAME = 'ITEMS PARSER'
const SERVER_PORT = 3002
const URLS_TO_PARSE_LIMIT = 100
const PARSING_DEADLINE_TIMEOUT_VALUE = 1
const PARSING_DEADLINE_TIMEOUT_MEASURE = 'm'

const JSON_DATA_PATH = '../../json-data/categoriePages/'

const PARSING_STATUS_NOT_REQUESTED = 'NOT_REQUESTED'
const PARSING_STATUS_IN_PROGRESS = 'PROGRESS'
const PARSING_STATUS_DONE = 'DONE'

const parsingStates = {
  PARSING_STATUS_NOT_REQUESTED,
  PARSING_STATUS_IN_PROGRESS,
  PARSING_STATUS_DONE,
}

module.exports.default = {
  SERVER_NAME,
  SERVER_PORT,
  URLS_TO_PARSE_LIMIT,
  JSON_DATA_PATH,
  PARSING_DEADLINE_TIMEOUT_VALUE,
  PARSING_DEADLINE_TIMEOUT_MEASURE,
}

module.exports.parsingStates = parsingStates


